synced_files:
  - python-deprecated.spec
  - .packit.yml
upstream_package_name: Deprecated
upstream_tag_template: v{version}
downstream_package_name: python-deprecated
jobs:
- job: propose_downstream
  trigger: release
  metadata:
    dist_git_branches:
    - fedora-all
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
    - fedora-all
