# What Python version is installed where:
# http://www.appveyor.com/docs/installed-software#python

version: 1.2.14.{build}

environment:
  matrix:
    # Python **2.6** and **3.3** are no more supported
    - PYTHON: "C:\\Python27"
      TOX_ENV: "py27"

    - PYTHON: "C:\\Python27-x64"
      TOX_ENV: "py27"

    - PYTHON: "C:\\Python35"
      TOX_ENV: "py35"

    - PYTHON: "C:\\Python35-x64"
      TOX_ENV: "py35"

    - PYTHON: "C:\\Python36"
      TOX_ENV: "py36"

    - PYTHON: "C:\\Python36-x64"
      TOX_ENV: "py36"

    - PYTHON: "C:\\Python37"
      TOX_ENV: "py37"

    - PYTHON: "C:\\Python37-x64"
      TOX_ENV: "py37"

    - PYTHON: "C:\\Python38"
      TOX_ENV: "py38"

    - PYTHON: "C:\\Python38-x64"
      TOX_ENV: "py38"

init:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;C:\MinGW\msys\1.0\bin;%PATH%
  - "git config --system http.sslcainfo \"C:\\Program Files\\Git\\mingw64\\ssl\\certs\\ca-bundle.crt\""
  - "%PYTHON%\\python.exe -V"
  - "%PYTHON%\\python.exe -c \"import struct;print(8 * struct.calcsize(\'P\'))\""

install:
  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe -m pip install tox"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - "%PYTHON%\\Scripts\\tox.exe -e %TOX_ENV%"

after_test:
  - "%PYTHON%\\python.exe setup.py --command-packages wheel bdist_wheel"
  - ps: "ls dist"

artifacts:
  - path: dist\*
